### ISSUE TITLE
Let's have a single less loader plugin

### ISSUE THREAD

**Issue by ffflabs** [systemjs/plugin-less#10]
I'm the author of [systemjs-less-plugin](https://github.com/HuasoFoundries/systemjs-less-plugin), which has got quite some traction, zero dependencies, and has just got a the feature of updating its bundle of npm:less both for node and browser.

What do you think if I transfer that repo to this organization so we provide one canonical less loader plugin?

**Comment by ffflabs** [comment]
I'll be out on vacation for a couple of weeks. If you find this note and agree, ping me in this same thread.

**Comment by guybedford** [comment]
It would definitely be great to have a single project and to shift responsibility to that.

This project includes these features though, which I'd be worried about losing:
* The ability to output separate CSS file parallel to the build
* CSS and LESS are all minified and run through autoprefixer as well as CSS minification and deduplication together as part of the build process. This is why there was an effort to standardize on a single base css loader in https://github.com/systemjs/plugin-css.
* CSS source maps are carefully implement here to work in development and production

How does systemjs-less-plugin deal with the above?

I'm unable to continue to maintain this plugin myself, so would definitely be interested in help of some form.

**Comment by ffflabs** [comment]
I will implement the features you mention and get back at you with that. And of course I'll still take on the responsibility of mantaining the resulting repo once it is on the systemjs organization.

I'll start by making my code pass the tests you have on this repo.

**Comment by ffflabs** [comment]
Long story short, I saw that I was mimicking the features that CSS plugin base already has, so I took your code and used it in my loader file. This means my plugin is now a children of this one, but it has a built workflow that bundles less.

This takes away the pain of dealing with node_modules folder, which in my case is not in the public folder.

So, what should we do? You can either add me to this repo and I'll add the less bundling workflow and the (few) mocha tests to have the best of both worlds **or** I can transfer my plugin to you or this organization, and we mark this one as deprecated **or** I mark mine as deprecated, point to this one and life goes on.

**Comment by guybedford** [comment]
@amenadiel excellent, thank you for the update! This looks really great, I'd be happy to make this project the default less plugin for jspm. If you'd like to post a registry PR to set this, I will accept it asap.
