### ISSUE TITLE
Export a compiled CSS as text?

### ISSUE THREAD

**Issue by diagramatics** [systemjs/plugin-less#3]
Now I'm not sure how to handle this, but we're using JSPM and SystemJS and we want to get the compiled CSS as text stored in an exported variable. Something like:

``` js
import style from './styles.less';
```

I could fork this plugin and spin up my own variant but I was wondering if I can do it in such a way that I can bring this upstream — that is, if you think it's suitable for it.

**Comment by guybedford** [comment]
You could do this with the text plugin rather than the less plugin:

``` javascript
System.config({
  meta: {
    "styles/*.less": { loader: 'text' }
  }
});
```

**Comment by diagramatics** [comment]
Unfortunately we still need to compile them into CSS as well before doing that, but I think I've established that I might need to fork anyway since we need Autoprefixer.

**Comment by diagramatics** [comment]
Closing since it's now a non-issue.
